### ISSUE TITLE
htmlcompressor failed to compress html

### ISSUE THREAD

**Issue by AlbanMinassian** [jney/grunt-htmlcompressor#4]
Bonjour

Quand ce message s'affiche, on n'est pas en mesure d'identifier le fichier qui pose problème. 
- Pouvez-vous améliorer ce message en y ajoutant le nom du fichier qui pose problème 
- pouvez-vous aussi afficher les erreurs retournés par htmlcompressor car on n'identifie pas du tout le problème !

Cordialement
Ami44

**Comment by jney** [comment]
Bonjour,

c'est la manière standard de gérer les erreurs, cf : https://github.com/gruntjs/grunt-contrib-coffee/blob/master/tasks/coffee.js#L81-82
Quelle est l'erreur affichée ? Aucun fichier de log n'est générer ? 

Cdt

**Comment by jney** [comment]
pas de retour, je clos la note

**Comment by kurttheviking** [comment]
I stumbled on this myself while building a new project with this grunt module. `stdout` does not display any specific error information--just the following

```
ERROR
htmlcompressor failed to compress html
```

It turned out that this was happening because the machine did not have a JRE installed. (htmlcompressor requires Java). Quick fix was to run `sudo apt-get install default-jre`

**Comment by oaleynik** [comment]
Hi there,

I've faced the same problem on Windows 8 x64: htmlcompressor failed to compress html. Running Grunt with --verbose param shows that "java not found". However, jre is installed on the machine and it is present in the system path. I've fixed it by this way (the ugly way) - in grunt-htmlcompressor.js replaced 'java' with the absolute path to java executable. Any suggestions how to fix it in a correct way?

**Comment by marcosgallardo** [comment]
For Windows another workaround will be update "PATH" environment variable buy adding the path to "java.exe", for example:
Start > Right click over "Computer" > Properties >  Advanced system configuration > Advanced options (tab) > Enviroment vars (button) > Edit PATH and add path to "java.exe" (..;C:\Program Files (x86)\Java\jre7\bin)

NOTE: If you have cmd open, close it and open it again, otherwise will not work.
